version: 2
updates:
  - package-ecosystem: npm
    directory: "/pkg/js/avers"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
